Fixes binary duplicated names
NVIDIA/NVTabular pull request #437
Opened 2020-11-17 05:10 UTC by albert17

When using HugeCTR Format, we were having duplicated filenames when using dask, updated to work in the same way that parquet is workig.

I think for version 0.4, we should be improving the HugeCTR writer, to look similar to Parquet, and support not only Binary but also Norm format.

2020-11-17 05:27 UTC, benfred approved these changes

2020-11-17 17:31 UTC, benfred commented
rerun tests

2020-11-17 17:34 UTC, benfred commented
rerun tests

2020-11-18 00:20 UTC, benfred commented on nvtabular/io/hugectr.py
> +            self.data_paths = [os.path.join(out_dir, f"{i}.data") for i in range(self.num_out_files)]
Looks like black doesn't like this : 
```suggestion
        if self.use_guid:
            self.data_paths = [
                os.path.join(out_dir, f"{i}i.{guid()}.data") for i in range(self.num_out_files)
            ]
        else:
            self.data_paths = [
                os.path.join(out_dir, f"{i}.data") for i in range(self.num_out_files)
            ]
```

also you might want to install the precommit hook here to catch this automatically:

```
#  from https://pre-commit.com/ - inside the nvtabular go:
pip install precommit
precommit install
```

2020-11-18 00:42 UTC, benfred requested changes
I don't think this is working - flake8 is complaining about:
```
./nvtabular/io/hugectr.py:28:47: F821 undefined name 'guid'
```

2020-11-18 01:15 UTC, albert17 commented
Sorry, CI was not working  yesterday night and I didn't realized. I have updated.

2020-11-18 01:23 UTC, benfred commented
> Sorry, CI was not working yesterday night and I didn't realized. I have updated.

No worries - installing the precommit hook will take about 1 minute and would catch issues like this though before hitting CI =) (follow the steps here https://pre-commit.com/ - the config file is already checked in).

2020-11-18 01:23 UTC, benfred approved these changes

2020-11-18 01:23 UTC, merged