[REVIEW] Fix get_emb_size bug when feeding num_buckets as an int to Categorify
NVIDIA/NVTabular pull request #544
Opened 2021-01-29 23:18 UTC by rnyak

This PR fixes the bug reported in this issue https://github.com/NVIDIA/NVTabular/issues/543.

2021-01-29 23:20 UTC, benfred requested changes
Can you add a unit test that tests out get_embedding_sizes with an int numbuckets passed to categorify?

2021-01-29 23:20 UTC, benfred commented on _config.yml
> +theme: jekyll-theme-cayman
Did you mean to check this file in?

2021-01-29 23:38 UTC, rnyak commented on _config.yml
> +theme: jekyll-theme-cayman
it was mistakenly generated. Idk how.

2021-02-01 17:09 UTC, benfred approved these changes

2021-02-01 17:09 UTC, merged