(WIP) PyTorch Dataloader support for multi-GPU training w/ Horovod
NVIDIA/NVTabular pull request #674
Opened 2021-03-23 15:57 UTC by karlhigley

This is a working training script for the Movielens example with multiple GPUs but no data partitioning. (All workers train on exactly the same data, since the dataloader itself doesn't yet have support for partitioning the data across workers.)

2021-03-29 17:52 UTC, jperez999 commented
Can we add the pytorch script to the examples/horovod or move the tf script and the hvd_wrapper.sh file to the appropriate directory (i.e. examples/multi-gpu...)?

2021-03-29 18:21 UTC, jperez999 requested changes

2021-03-29 18:30 UTC, karlhigley commented on nvtabular/loader/backend.py
> +        seed_fn=None,
Yeah, happy to open another PR to add it to the TF side.

2021-03-29 18:31 UTC, karlhigley commented on nvtabular/loader/backend.py
> +        self.indices = indices or cp.arange(dataset.to_ddf().npartitions)
Good catch, missed this in the merge conflict resolution.

2021-03-29 18:31 UTC, karlhigley commented on tests/unit/test_torch_dataloader.py
> +            "examples/multi-gpu/torch-nvt-horovod.py",
Yeah, we definitely should. I'll borrow it from your PR.

2021-03-30 20:58 UTC, benfred approved these changes
looks great!

2021-03-30 23:47 UTC, jperez999 approved these changes

2021-03-30 23:54 UTC, benfred approved these changes

2021-03-30 23:59 UTC, merged